### ISSUE TITLE
error on generateUrl

### ISSUE THREAD

**Issue by Mumin** [toniov/gcal-cli#3]
Tried on Mac as described in readme. 

Got 

(ts)-(jobs:0)-(~)
(! 620)-> gcal --config /Users/ts/client_secret.json generateUrl
[ERROR] Cannot match against 'undefined' or 'null'.

**Comment by toniov** [comment]
Hi!

You can not pass directly the credentials path as argument, you need to pass a config file that contains your desired path for the credentials.

In your case it would be something like this (explained [here](https://github.com/toniov/gcal-cli#overwriting-default-config) ):

Create `/somepath/config.json` with this content:
```json
{
  "CRED_PATH": "/Users/ts/client_secret.json"
}
```

Then execute the command:
`$ gcal -C /somepath/config.json generateUrl`

**Comment by Mumin** [comment]
thanks. Tested as you suggest but still not working and error message is not really self explaining ;-)

(ts)-(jobs:0)-(~/gcal)
(! 631)-> gcal -C /Users/ts/gcal/config.json generateUrl
[ERROR] Cannot match against 'undefined' or 'null'.

(ts)-(jobs:0)-(~/gcal)
(! 632)-> ls
client_secret.json	config.json

(ts)-(jobs:0)-(~/gcal)
(! 633)-> cat config.json 
{
  "CRED_PATH": "/Users/ts/gcal/client_secret.json"
}

**Comment by toniov** [comment]
If you include the option `--debug` at the end we can get the error stack.

How is the format of your `client_secret.json` file? It expects something in this format:

```json
{
  "installed": {
    "client_id": "foo",
    "client_secret": "bar",
    "redirect_uris": [
      "urn:baz",
      "http://localhost"
    ]
  }
}
```

**Comment by Mumin** [comment]
here is my content (download right away from Google "download json" option). secret parts have been replaced by ...
{
"web:{"client_id":"....apps.googleusercontent.com","project_id":"...","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"..."}
}

**Comment by toniov** [comment]
I see, when you create your client ID you must choose `Other` in `Application type`, not `Web`.

I'll fix the README specifying it!
