### ISSUE TITLE
storeToken results in an error

### ISSUE THREAD

**Issue by Mumin** [toniov/gcal-cli#4]
Have gone through token generation via URL generated by gcal generateUrl. 
Code was successfully generated via this URL but storeToken delivers error:

(! 642)-> gcal -C /Users/ts/gcal/config.json storeToken [token]
[ERROR] invalid_grant

**Comment by toniov** [comment]
That error happens when you reuse the code. Did you use it more than once?

Try to get a new code and execute `storeToken` again. There is a good explanation about the tokens that Google returns [here](https://stackoverflow.com/a/32710034/6254875).

**Comment by SantoshSrinivas79** [comment]
I'm getting the same error on using a new code too.

**Comment by toniov** [comment]
Thanks for the report, I found a bug parsing the argument of storeToken. It's already fixed and released as a patch version.

Update the app and try again!

**Comment by SantoshSrinivas79** [comment]
@toniov Thank you. Works now!

**Comment by toniov** [comment]
It seems it's solved so closing the issue!
